### ISSUE TITLE
Login redirect issue with version 6.13.4 and hash routing

### ISSUE THREAD

**Issue by noherczeg** [AxaFrance/react-oidc#942] opened 2023-01-24 00:30 UTC
### Issue and Steps to Reproduce

Since I upgraded the lib version, login redirects are no longer working (using keycloak).

The redirected URL looks like this: `http://localhost:8181/segment1/segment2/?state=8UcnF9CH02&session_state=2e017564-83e4-49bf-93dc-3151549da447&code=e4d81518-952f-4695-82bd-f53cd683bdb5.2e017564-83e4-49bf-93dc-3151549da447.f24f6894-83f5-402a-8a7c-1f166dc940a8#/authentication/callback`

I assume the problem is that for some reasone the library is positioning the request param `?state` after `window.location.origin` instead of the provided `redirect_uri` configuration?

I guess it should look like this: `http://localhost:8181/segment1/segment2/#/authentication/callback?state=8UcnF9CH02&session_state=2e017564-83e4-49bf-93dc-3151549da447&code=e4d81518-952f-4695-82bd-f53cd683bdb5.2e017564-83e4-49bf-93dc-3151549da447.f24f6894-83f5-402a-8a7c-1f166dc940a8`

The single page app root is: `http://localhost:8181/segment1/segment2/#/`

### Versions
6.13.4

#### Expected
To be redirect to the provided url

#### Actual
Request param probably placed in the wrong section of the URL sabotaging the server route handler.

### Additional Details

- Installed packages:

**Comment by noherczeg** [comment] 2023-01-24 01:21
The value of `oidc.login.default` is `{"callbackPath":"/segment1/segment2/","extras":null}`. Guess this should also be `{"callbackPath":"/segment1/segment2/#/authentication/callback/","extras":null}`

**Comment by noherczeg** [comment] 2023-01-24 01:31
Okay so `const callbackPath = (0, route_utils_1.getPath)(redirect_uri);` besides I don't know what else is bugged for sure.

Produces: `"/segment1/segment2#/authentication/callback"` instead of: `"segment1/segment2/#/authentication/callback"`

**Comment by noherczeg** [comment] 2023-01-24 01:33
Not sure if this has anything to do with the issue: `const url = callbackPath || location.pathname + (location.search || '') + (location.hash || '');`

**Comment by noherczeg** [comment] 2023-01-24 01:57
Also: `const oidc = getOidc(configurationName)` in `SilentCallback.component.tsx` returns

oidc._oidc.configuration.silent_redirect_uri: `"http://localhost:8181/segment1/segment2/#/authentication/callback"` which is not the configured `silent_redirect_uri` BUT the `redirect_uri`.

**Comment by guillaume-chervet** [comment] 2023-01-24 12:08
Hi @noherczeg , i cannot reproduce the problem.
What does look like your  configuration?

**Comment by noherczeg** [comment] 2023-01-24 13:07
@guillaume-chervet 

```
{
  authority: "http://localhost:8080/auth/realms/MULTIADMIN",
  client_id: "MultiPrincipalTest-admin-Admin",
  redirect_uri: "http://localhost:8181/MultiPrincipalTest/multiprincipaltest__admin__admim/#/authentication/callback",
  refresh_time_before_tokens_expiration_in_second: 15,
  scope: "email openid",
  service_worker_only: false,
  silent_redirect_uri: "http://localhost:8181/MultiPrincipalTest/multiprincipaltest__admin__admin/#/authentication/callback"
}
```

**Comment by noherczeg** [comment] 2023-01-24 17:34
Okay the problem is with the redirect uri. In my case I had to use the router's root, and also add a manual cleanup, because the `?state...` search params never got removed.

Hope this will help others.

**Comment by guillaume-chervet** [comment] 2023-01-25 17:20
hi @noherczeg ,

i cannot reproduce it.
Does your application configuration work with:

```js
export const configurationIdentityServerWithHash = {
    client_id: 'interactive.public.short',
    redirect_uri: window.location.origin + '/multi-auth/authentification/#/authentication-callback',
    silent_redirect_uri: window.location.origin + '/multi-auth/authentification/#/authentication-silent-callback',
    // silent_login_uri: window.location.origin + '/multi-auth/authentification/#/authentication-silent-login',
    scope: 'openid profile email api offline_access',
    authority: 'https://demo.duendesoftware.com',
    refresh_time_before_tokens_expiration_in_second: 10,
    // service_worker_relative_url: '/OidcServiceWorker.js',
    // service_worker_only: false,
};
```

**Comment by noherczeg** [comment] 2023-01-25 17:48
@guillaume-chervet Thanks for the tip, we'll check it later. Since we managed to apply a workaround for our issue, please don't spend too much time with this! :)

Cheers!

**Comment by guillaume-chervet** [comment] 2023-05-05 20:43
Hi @noherczeg , thank you. I close the issue but feel free to reopen it if you need.

**Closed by guillaume-chervet** 2023-05-05 20:43 UTC
